### ISSUE TITLE
How can l use this code for graph classification ?

### ISSUE THREAD

**Issue by Benjiou** [benedekrozemberczki/GraphWaveletNeuralNetwork#2]
Hi @benedekrozemberczki ,

Let me first thank you for this promising work. 

I would like to  apply your GWNN to graph  classification  problems rather than nodes classification.

Do you have any extension for that ?

Thank you

**Comment by benedekrozemberczki** [comment]
If You pass me a dataset which is in line with the classification formatting I can write an extension. Also it requires a few lines to be modified so feel free to create a pull request. If You do so please add a test dataset and modify the readme and so on.

**Comment by Benjiou** [comment]
Hi @benedekrozemberczki ,

Thank you for your answer.

You can use MNIST classifcation, where each example is a 2d regular graph. Each pixel is a node. Hence you will get a graph of 28*28=784 nodes where each node is a pixel.

ChebNet GCN did that.
Here is how to build MNIST graphs for classification 
https://github.com/xbresson/spectral_graph_convnets/blob/master/02_graph_convnet_lenet5_mnist_pytorch.ipynb
From the work of  M Defferrard, X Bresson, P Vandergheynst  "Convolutional Neural Networks on Graphs with Fast Localized Spectral Filtering"

```
#Get MNIST data
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('datasets', one_hot=False) # load data in folder datasets/

train_data = mnist.train.images.astype(np.float32)
val_data = mnist.validation.images.astype(np.float32)
test_data = mnist.test.images.astype(np.float32)
train_labels = mnist.train.labels
val_labels = mnist.validation.labels
test_labels = mnist.test.labels
print(train_data.shape)
print(train_labels.shape)
print(val_data.shape)
print(val_labels.shape)
print(test_data.shape)
print(test_labels.shape)
```

```
# Build graphs
from lib.grid_graph import grid_graph
from lib.coarsening import coarsen
from lib.coarsening import lmax_L
from lib.coarsening import perm_data
from lib.coarsening import rescale_L

# Construct graph
t_start = time.time()
grid_side = 28
number_edges = 8
metric = 'euclidean'
A = grid_graph(grid_side,number_edges,metric) # create graph of Euclidean grid

# Compute coarsened graphs
coarsening_levels = 4
L, perm = coarsen(A, coarsening_levels)

# Compute max eigenvalue of graph Laplacians
lmax = []
for i in range(coarsening_levels):
    lmax.append(lmax_L(L[i]))
print('lmax: ' + str([lmax[i] for i in range(coarsening_levels)]))

# Reindex nodes to satisfy a binary tree structure
train_data = perm_data(train_data, perm)
val_data = perm_data(val_data, perm)
test_data = perm_data(test_data, perm)

print(train_data.shape)
print(val_data.shape)
print(test_data.shape)

print('Execution time: {:.2f}s'.format(time.time() - t_start))
del perm
```
I'm curious to see if WGNN outperforms also ChebNet in whole graph classification.

Thank you

**Comment by ahmedmazariML** [comment]
Hi @benedekrozemberczki  & @Benjiou 

I am also interested in the answer.

Thank you

**Comment by benedekrozemberczki** [comment]
If your graphs in the graph database have the same number of nodes (e.g. MNIST images) you can make it work (the density of graphs might change). Still, you have to come up with a pooling procedure over the features. Importantly, if the number of vertices differs the diagonal filter matrix makes graph classification impossible. Essentially, by the use of the trainable diagonal filter the size of the graph is hard coded into the architecture.
