### ISSUE TITLE
Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by Evelyn-coder** [benedekrozemberczki/GraphWaveletNeuralNetwork#6]
hi, author. 
       These days i've been watching the program. But when I run on this code, I find an error happened during the time. Can you give me some suggestions?

![image](https://user-images.githubusercontent.com/37922973/78153259-70be5300-746d-11ea-8add-efe95362b05c.png)

![image](https://user-images.githubusercontent.com/37922973/78153285-7b78e800-746d-11ea-8f1d-2e00d1933894.png)

**Comment by Evelyn-coder** [comment]
![image](https://user-images.githubusercontent.com/37922973/78155115-a19f8780-746f-11ea-8b83-1ce2ddb2d5fc.png)

**Comment by benedekrozemberczki** [comment]
Wrong package versions or you hit a memory constraint.
