### ISSUE TITLE
what's the meanning of the "feature matrix"?

### ISSUE THREAD

**Issue by CindyTing** [benedekrozemberczki/GraphWaveletNeuralNetwork#7]
Hello author, sorry about a stupid question. But the Cora dataset has Cora.cites corresponding your cora_edges.csv, and Cora.content's paper index and paper category for your cora_target.csv, so I don't understand the meanning of your cora_features.json . In the beginning, I just think it's an adjacency matrix of all nodes(paper index), however, the content are inconsistent. Such as ,in cora_edges.csv it's as the picture as follw:
![image](https://user-images.githubusercontent.com/35062414/93728397-6302b280-fbf2-11ea-879e-7d22bd268d01.png)
and in cora_features.json it's :
![image](https://user-images.githubusercontent.com/35062414/93728491-b8d75a80-fbf2-11ea-9d78-34e0326698b7.png)
So I am confused , and hope for your answer. Thank you very much.

**Comment by CindyTing** [comment]
I understand, and I am so stupid, that's the index of bag of words. I am so sorry, thanks anyway.

**Comment by tanjia123456** [comment]
hello, could you plaese explain cora_feature.json for me? I use this in my own datasets, so i'm not understant the meanning of this format.

**Comment by CindyTing** [comment]
@tanjia123456 There is a dictionary composed of the word of all documents, each line of cora_feature.json represents the index of the word (in this document) in the dictionary.

**Comment by tanjia123456** [comment]
@CindyTing Can I understand it as the feature index corresponding to each node?

**Comment by CindyTing** [comment]
@tanjia123456 yeah, I think so.

**Comment by tanjia123456** [comment]
ok, thank you very much. I will try to make data in this format

**Comment by benedekrozemberczki** [comment]
Yes it is a sparse matrix in row column index format.
